# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener Dsicovery Server
name: gardener-discovery-server
version: 0.1.0
dependencies:
  - name: application
    version: 0.1.0
    condition: application.enabled
  - name: runtime
    version: 0.1.0
    condition: runtime.enabled
