# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    networking.resources.gardener.cloud/from-all-garden-scrape-targets-allowed-ports: '[{"protocol":"TCP","port":8080}]'
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 4 }}
  ports:
  - name: https
    port: 10443
    protocol: TCP
    targetPort: 10443
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: healthz
    port: 8081
    protocol: TCP
    targetPort: 8081
